name: Publish Docker images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-release:
    name: Build release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      repo: "govpf/pgsync-wrapper"
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2.7.0
      with:
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:${{ github.event.release.tag_name }}

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2.4.3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"

  build-dev:
    name: Build dev
    if: "!startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    env:
      repo: "govpf/pgsync-wrapper"
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2.7.0
      with:
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:latest

    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2.4.3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"