name: Build Docker image

on: pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      repo: "govpf/pgsync-wrapper"
    steps:

    - name: Checkout
      uses: actions/checkout@v3.0.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.1.0

    - name: Build and push
      uses: docker/build-push-action@v2.10.0
      with:
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:latest
